// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'asset_entity.freezed.dart';

part 'asset_entity.g.dart';

@freezed
class Asset with _$Asset {
  const factory Asset({
    required String id,
    required int rank,
    required String symbol,
    required String name,
    required double priceUsd,
  }) = _Asset;

  factory Asset.fromJson(Map<String, dynamic> json) => _$AssetFromJson(json);
}
