// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'price_entity.freezed.dart';

@freezed
class Price with _$Price {
  const factory Price({required String price}) = _Price;
}
