import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'price_model.freezed.dart';

part 'price_model.g.dart';

@freezed
class PriceDto with _$PriceDto {
  const factory PriceDto(Map<String, dynamic> data) = _PriceDto;

  factory PriceDto.fromJson(Map<String, Object?> json) =>
      _$PriceDtoFromJson(json);
}
